---
- hosts: web
  # debugger: always
  become: true
  tasks:
    - name: Install NTP
      apt:
        name: ntp
        state: present
    - name: Restart the NTP Service
      service:
        name: ntp
        state: restarted
    - name: Change the config ntp.conf
      lineinfile:
        path: /etc/ntp.conf
        insertafter: EOF
        line: 'server de.pool.ntp.org iburst'
    - name: Restart the NTP Service
      service:
        name: ntp
        state: restarted
